[package]
name = "typhon-webapp"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = [ "cdylib", "rlib" ]

[[bin]]
name = "typhon-webapp"
path = "src/main.rs"

[dependencies]
typhon-types = { path = "../typhon-types" }
once_cell = "1.16"
web-sys = { version = "0.3", features = ["Navigator", "Clipboard"] }
seed = "0.9"
serde = { version = "1.0", features = [ "derive" ] }
serde-wasm-bindgen = "0.4"
wasm-bindgen-futures = "0.4"
