[package]
name = "typhon-webapp"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = [ "cdylib", "rlib" ]

[[bin]]
name = "typhon-webapp"
path = "src/main.rs"

[dependencies]
typhon-types.workspace = true
async-stream.workspace = true
async-trait.workspace = true
futures-core.workspace = true
gloo-console.workspace = true
gloo-net.workspace = true
gloo-storage.workspace = true
once_cell.workspace = true
seed.workspace = true
serde-wasm-bindgen.workspace = true
serde.workspace = true
serde_json.workspace = true
time.workspace = true
wasm-bindgen-futures.workspace = true
web-sys.workspace = true
