[package]
name = "typhon-webapp"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = [ "cdylib", "rlib" ]

[[bin]]
name = "typhon-webapp"
path = "src/main.rs"

[dependencies]
typhon-types = { path = "../typhon-types" }
seed = "0.9"
