[package]
name = "typhon-webapp"
version.workspace = true
edition.workspace = true

[lib]
crate-type = [ "cdylib", "rlib" ]

[dependencies]
typhon-lib = { workspace = true, optional = true }
typhon-types.workspace = true
async-stream.workspace = true
async-trait.workspace = true
futures-core.workspace = true
gloo-console.workspace = true
gloo-net.workspace = true
gloo-storage.workspace = true
gloo-utils.workspace = true
js-sys.workspace = true
leptos = { workspace = true, features = ["nightly"] }
serde-wasm-bindgen.workspace = true
serde.workspace = true
serde_json.workspace = true
time.workspace = true
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
web-sys.workspace = true

[features]
default = []
hydrate = ["leptos/hydrate"]
ssr = ["dep:typhon-lib", "leptos/ssr"]
