[workspace]
members = [
  "typhon",
  "typhon-types",
  "typhon-webapp",
  "typhon-api-client-test",
]
default-members = [
  "typhon"
]
resolver = "2"

[workspace.dependencies]
typhon-types = { path = "./typhon-types" }
actix = "0.13"
actix-cors = "0.6"
actix-files = "0.6"
actix-web = "4.2"
actix-web-actors = "4.1"
age = { version = "0.8", features = ["armor"] }
async-stream = "0.3"
async-trait = "0.1"
clap = { version = "4.0", features = ["derive"] }
colored = "2"
diesel = { version = "2.0.2", features = ["sqlite", "returning_clauses_for_sqlite_3_35"] }
diesel_migrations = "2.0"
futures = "0.3"
futures-core = "0.3"
log = "0.4"
once_cell = "1.16"
seed = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.4"
serde_json = "1.0"
serde_repr = "0.1"
sha256 = "1.1"
stderrlog = "0.5"
substring = "1.4"
surf = "2.3"
tokio = { version = "1.22", features = ["full"] }
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["Navigator", "Clipboard", "ReadableStream", "Response"] }
