[workspace]
members = [
  "typhon",
  "typhon-types",
  "typhon-webapp",
]
default-members = [
  "typhon"
]
resolver = "2"

[workspace.dependencies]
typhon-types = { path = "./typhon-types" }
actix = "0.13"
actix-cors = "0.6"
actix-files = "0.6"
actix-web = "4.4"
age = { version = "0.8", features = ["armor"] }
async-stream = "0.3"
async-trait = "0.1"
clap = { version = "4.4", features = ["derive"] }
diesel = { version = "2.1", features = ["sqlite", "returning_clauses_for_sqlite_3_35", "r2d2"] }
diesel_migrations = "2.1"
futures = "0.3"
futures-core = "0.3"
gloo-console = "0.3"
gloo-net = "0.4"
gloo-storage = "0.3"
gloo-utils = "0.2"
js-sys = "0.3"
lazy_static = "1.4"
leptos = { version = "0.5", features = ["csr", "nightly"] }
log = "0.4"
once_cell = "1.18"
regex = "1.10"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.4"
serde_json = "1.0"
serde_repr = "0.1"
sha256 = "1.4"
stderrlog = "0.5"
substring = "1.4"
time = { version = "0.3", features = ["serde"] }
tokio = { version = "1.33", features = ["full"] }
tokio-stream = "0.1"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["Navigator", "Clipboard", "ReadableStream", "Response"] }
