[package]
name = "typhon-api-client-test"
version = "0.0.1"
edition = "2021"

[dependencies]
typhon-types.workspace = true
async-trait.workspace = true
colored.workspace = true
serde.workspace = true
serde_json.workspace = true
surf.workspace = true
tokio.workspace = true
