[package]
name = "typhon-api-client-test"
version = "0.0.1"
edition = "2021"

[dependencies]
typhon-types = { path = "../typhon-types" }
serde = "1.0"
serde_json = "1.0"
tokio = { version = "1.22", features = [ "full" ] }
surf = "2.3"
async-trait = "0.1.4"
colored = "2"
