[package]
name = "typhon"
version = "0.0.1"
edition = "2021"
authors = [ "Paul-Nicolas Madelaine <pnm@pnm.tf>" ]

[dependencies]
actix = "0.13"
actix-cors = "0.6"
actix-web = "4.2"
actix-web-actors = "4.1"
age = { version = "0.8", features = [ "armor" ] }
async-stream = "0.3"
async-trait = "0.1.4"
clap = { version = "4.0", features = [ "derive" ] }
diesel = { version = "2.0.2", features = [ "sqlite", "returning_clauses_for_sqlite_3_35" ] }
diesel_migrations = "2.0"
futures = "0.3"
futures-core = "0.3"
log = "0.4"
once_cell = "1.16"
serde = "1.0"
serde_json = "1.0"
sha256 = "1.1"
stderrlog = "0.5"
substring = "1.4"
tokio = { version = "1.22", features = [ "full" ] }
typhon-types = { path = "../typhon-types" }
