[package]
name = "typhon-types"
version = "0.0.1"
edition = "2021"

[dependencies]
lazy_static.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
time.workspace = true
